### ISSUE TITLE
Question - TypeScript-like syntax in createActions objects

### ISSUE THREAD

**Issue by mnoster** [gilbarbara/react-redux-saga-boilerplate#30]
In the `scripts/actions/app.js` within the `createActions` function, an object is being passed with a dynamic key and a function as a value. This function has a `query: string` argument and shows distinct similarity to TypeScript syntax.

Example:

```
createActions({
  [ActionTypes.SWITCH_MENU]: (query: string) => ({ query }),
``` 

**I am curious to how this is possible given the `.js` file type.**

I looked into the `redux-actions` library but could not find any reference to this implementation with the type. 

The project compiles and runs fine with leaving the types in or taking them out.

 Thanks,

**Comment by gilbarbara** [comment]
Hey @mnoster!

It's [flow](https://flow.org/), a static type checker for javascript. The types are removed from the bundle by Babel (with [@babel/plugin-transform-flow-strip-types](https://babeljs.io/docs/en/babel-plugin-transform-flow-strip-types)).
Since you can enable it individually with the pragma `// @flow` on the top of the file it's a simple way to start typing your code.

**Comment by mnoster** [comment]
Thank you @gilbarbara for the explanation.

I didn't even know flow existed. Seems like a pretty cool technology if you don't want to fully migrate to TypeScript.

Great project by the way, I'm a big fan of sagas.

**Comment by gilbarbara** [comment]
Thanks! <3
